# Generated by Django 4.1.2 on 2023-01-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_application', '0002_remove_target_by_years_kpi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearly_plan',
            name='last_year_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
